// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRmKBM5uDKYlQjaaXZ3n68SX1ZXHYVOA',
    appId: '1:830454186141:web:7a99c6b9eb8b38b1bb9474',
    messagingSenderId: '830454186141',
    projectId: 'gymapp-6ddd2',
    authDomain: 'gymapp-6ddd2.firebaseapp.com',
    storageBucket: 'gymapp-6ddd2.firebasestorage.app',
    measurementId: 'G-2Z1CH66RDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdeyoMBIEGmb3HuSnIqDvxI46yZeCH3qM',
    appId: '1:830454186141:android:a43ad221f3308757bb9474',
    messagingSenderId: '830454186141',
    projectId: 'gymapp-6ddd2',
    storageBucket: 'gymapp-6ddd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPXwzIzlcFJ3vKBa2_59qc1J3lemqiBc',
    appId: '1:830454186141:ios:abca28bf86147a5abb9474',
    messagingSenderId: '830454186141',
    projectId: 'gymapp-6ddd2',
    storageBucket: 'gymapp-6ddd2.firebasestorage.app',
    iosBundleId: 'com.example.gymApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPXwzIzlcFJ3vKBa2_59qc1J3lemqiBc',
    appId: '1:830454186141:ios:abca28bf86147a5abb9474',
    messagingSenderId: '830454186141',
    projectId: 'gymapp-6ddd2',
    storageBucket: 'gymapp-6ddd2.firebasestorage.app',
    iosBundleId: 'com.example.gymApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRmKBM5uDKYlQjaaXZ3n68SX1ZXHYVOA',
    appId: '1:830454186141:web:9b2c9164b7a7089bbb9474',
    messagingSenderId: '830454186141',
    projectId: 'gymapp-6ddd2',
    authDomain: 'gymapp-6ddd2.firebaseapp.com',
    storageBucket: 'gymapp-6ddd2.firebasestorage.app',
    measurementId: 'G-HG5SVBE6JP',
  );
}
